auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:year:month:day:hour:minite

title: longstreetcc
url: http://longstreetcc.github.io
feed: /atom.xml
author_info: <a href="http://longstreetcc.github.io">longstreetcc</a>
