auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:year:month:day

title: longstreetcc
url: http://longstreetcc.github.io
feed: /feed
author_info: <a href="http://longstreetcc.github.io">longstreetcc</a>
